---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/app
      sourceRef:
        kind: GitRepository
        name: deploy
  interval: 30s
  targetNamespace: staging
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: test.arthurbdiniz.com
          paths: ['/*']