---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: deploy
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: deploy
  url: https://github.com/arthurbdiniz/flux-poc
