---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: deploy
  validation: client